version: '3'

services:
  web:
    build: .
    command: gunicorn hj_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data/
    environment:
      - POSTGRES_USER=hj_blog_db_user
      - POSTGRES_PASSWORD=hj_blog_db_password
      - POSTGRES_DB=hj_blog_dev
volumes:
  postgres_data: